#!/usr/bin/env bash
# PostToolUse hook: lint a single C++ file after Edit/Write.
# Reads tool input JSON on stdin, filters to foo_hemusic/{src,tests} C++
# sources, runs clang-tidy against foo_hemusic/build/compile_commands.json
# (generated by the Ninja Multi-Config build), and injects diagnostics back
# into Claude's context (non-blocking).

set -uo pipefail

input="$(cat)"
file="$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_response.filePath // empty')"
[ -z "$file" ] && exit 0

norm="${file//\\//}"
case "$norm" in
  */foo_hemusic/src/*|*/foo_hemusic/tests/*) ;;
  *) exit 0 ;;
esac
case "$norm" in
  *.cpp|*.cxx|*.cc|*.h|*.hpp|*.hxx) ;;
  *) exit 0 ;;
esac

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
build_dir="$repo_root/foo_hemusic/build"
[ -f "$build_dir/compile_commands.json" ] || exit 0

# Resolve clang-tidy. Fold in $CLANG_TOOLS_DIR (hooks get a narrow PATH);
# `command -v` resolves the .exe suffix on Windows. No-op if absent.
[ -n "${CLANG_TOOLS_DIR:-}" ] && PATH="$CLANG_TOOLS_DIR:$PATH"
tidy="$(command -v clang-tidy 2>/dev/null || true)"
[ -z "$tidy" ] && exit 0

output="$("$tidy" --quiet -p "$build_dir" "$file" 2>&1)"

if printf '%s' "$output" | grep -qE '(warning|error):'; then
  ctx=$'clang-tidy diagnostics for '"$(basename "$file")"$':\n\n'"$output"$'\n\nFix these before continuing.'
  jq -n --arg ctx "$ctx" '{
    hookSpecificOutput: {
      hookEventName: "PostToolUse",
      additionalContext: $ctx
    }
  }'
fi

exit 0
